### ISSUE TITLE
Implement Swagger 

### ISSUE THREAD

**Issue by aimanafzal** [SubsonicGroupFinder/SGF-web-app#46]
Implement Swagger with complete documentation of APIs

**Comment by aimanafzal** [comment]
@rr-phillips @Subsonic-dev Do you agree?

**Comment by rr-phillips** [comment]
@aimanafzal Yeah, that sounds good. Early and good documentation is always the way to go in my opinion

**Comment by Subsonic-dev** [comment]
Yup I just checked in on this as wasn't familiar with it. Are you familiar with this system @aimanafzal ? 

Linking it here for future reference:
https://swagger.io/

**Comment by aimanafzal** [comment]
> Yup I just checked in on this as wasn't familiar with it. Are you familiar with this system @aimanafzal ?
> 
> Linking it here for future reference:
> https://swagger.io/

Yes, I am 100% familiar with Swagger and used it for long term documentation. 
It is one of most reliable platforms to be used for internal API/Technical web based documentation which could be directly executed within the project.

**Comment by Subsonic-dev** [comment]
> 
> 
> > Yup I just checked in on this as wasn't familiar with it. Are you familiar with this system @aimanafzal ?
> > Linking it here for future reference:
> > https://swagger.io/
> 
> @Subsonic-dev Yes, I am 100% familiar with Swagger and used it for long term documentation.
> It is one of most reliable platforms to be used for internal API/Technical web based documentation which could be directly executed within the project.

Alrighty then if you're familiar with it go for it. As Rebeca said above the earlier we get good documentation going the better so Swagger is green lit from here on out. Seeing as you're familiar with it can you please handle its implementation.

**Comment by aimanafzal** [comment]
> > > Yup I just checked in on this as wasn't familiar with it. Are you familiar with this system @aimanafzal ?
> > > Linking it here for future reference:
> > > https://swagger.io/
> > 
> > 
> > @Subsonic-dev Yes, I am 100% familiar with Swagger and used it for long term documentation.
> > It is one of most reliable platforms to be used for internal API/Technical web based documentation which could be directly executed within the project.
> 
> Alrighty then if you're familiar with it go for it. As Rebeca said above the earlier we get good documentation going the better so Swagger is green lit from here on out. Seeing as you're familiar with it can you please handle its implementation.

Sure.. I will take care of it. 
Can you assign this issue to me? As I have already started working on it.

**Comment by aimanafzal** [comment]
@Subsonic-dev Please assign this task to me.

**Comment by Subsonic-dev** [comment]
@aimanafzal Assigned.

**Comment by aimanafzal** [comment]
Perfect @Subsonic-dev

**Comment by Subsonic-dev** [comment]
@aimanafzal Shall I close this issue or would you like it left open as an ongoing task? I merged your other requests.

**Comment by aimanafzal** [comment]
> @aimanafzal Shall I close this issue or would you like it left open as an ongoing task? I merged your other requests.

I'll close it and will re-visit if required. So far the documentation looks good based on what we have in the code itself.
